//add your constants here
export const GET_ALL_RANDOMIZE_MENUS_SUCCESS =
  'GET_ALL_RANDOMIZE_MENUS_SUCCESS';
export const GET_ALL_RANDOMIZE_MENUS_ERROR = 'GET_ALL_RANDOMIZE_MENUS_ERROR';
export const GET_ALL_MENUS_SUCCESS = 'GET_ALL_MENUS_SUCCESS';
export const GET_ALL_MENUS_ERROR = 'GET_ALL_MENUS_ERROR';
export const ADD_MENU_SUCCESS = 'ADD_MENU_SUCCESS';
export const ADD_MENU_ERROR = 'ADD_MENU_ERROR';
export const UPDATE_MENU_SUCCESS = 'UPDATE_MENU_SUCCESS';
export const UPDATE_MENU_ERROR = 'UPDATE_MENU_ERROR';
export const DELETE_MENU_SUCCESS = 'DELETE_MENU_SUCCESS';
export const DELETE_MENU_ERROR = 'DELETE_MENU_ERROR';
